### ISSUE TITLE
🐛 Bug: The validation of @class requires documentation that I think is unnecessary

### ISSUE THREAD

**Issue by ThosRTanner** [JoshuaKGoldberg/are-docs-informative#33]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/are-docs-informative/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

After raising this at https://github.com/gajus/eslint-plugin-jsdoc/issues/1039 I was redirected here.

I do not think @class requires any further detail n most context. It's just saying 'this is a class' and in pre ES6 code that is a very useful piece of information. 

### Actual

I expect to be able to use `@class` as a flag (as suggested in the jsdoc documentation) and not to have to provide further (and, it seems to me, unnecessary) information

### Additional Info

Please see the referenced issue.

I'm a bit lost here as it's not ME who is actually using this, it is another tool that is using this, but I think it is making the output of that tool unhelpful.

Also 'restarting my IDE' and 'pulling the latest branch' aren't really things I can do under the circumstances, but I seem to have no option but to tick them.

**Comment by JoshuaKGoldberg** [comment]
> as suggested in the jsdoc documentation

Interesting. I'm under the impression that the vast majority of projects these days use the `class` keyword to create classes. Can you provide a bit more context as to why you want to use `@class` still? E.g. why the `function MyAmazingThing` from https://github.com/gajus/eslint-plugin-jsdoc/issues/1039#issue-1677929118 isn't...

```js
/**
 * Some Description
 */
class MyAmazingThing {
  /**
   * @param {number} value - Some useful text
   */
  constructor(value) {
    this.thing = value;
  }
}
```

My read of https://jsdoc.app/tags-class.html is that it explains what the tag does, but doesn't explicitly say when or whether to use it.

> I'm a bit lost here as it's not ME who is actually using this

Apologies for the tangled web we've woven for you 🙂. `eslint-plugin-jsdoc`'s `informative-docs` rule works by:

1. Collecting the list of descriptions and `@` tags in each JSDoc
2. For each of those descriptions+tags, asking this package (`are-docs-informative`) whether they're informative
3. Reporting an ESLint complaint for any that weren't informative

...which is why you were redirected here. https://github.com/gajus/eslint-plugin-jsdoc/issues/1039 looks at first like an issue with how `are-docs-informative` is determining whether your `@class` comment is informative.

That being said, I hate to redirect you back to the other tool, but I think this actually is an issue in `eslint-plugin-jsdoc`'s `informative-docs` rule 😄. I sent a PR to fix just now: https://github.com/gajus/eslint-plugin-jsdoc/pull/1047

**Comment by ThosRTanner** [comment]
There's a couple of reasons really - firstly, this is legacy code that I'm trying to document before I start breaking bits, and secondly, in this particular system, I can't actually use the class keyword in some places as it confuses other parts of the system.

Thanks for looking at this and the workround. Much appreciated.

**Comment by JoshuaKGoldberg** [comment]
Since https://github.com/gajus/eslint-plugin-jsdoc/pull/1047 was merged and this issue has been stale, marking as closed. Thanks!
